//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TangNet;
namespace TangGame.Net
{
  public class StudySkillRequest : Request
  {
    private int skillIndex;
    /// <summary>
    /// 请求学习某一个技能
    /// </summary>
    /// <param name="skillIndex">Skill index.</param>
    public StudySkillRequest(int skillIndex)
    {
      this.skillIndex = skillIndex;
    }
    public NetData NetData
    {
      get
      {
        NetData data = new NetData(SkillProxy.S_STUDY_SKILL);
        data.PutInt(skillIndex);
        return data;
      }
    }
  }
}

