//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TangGame.Net
{
  /// <summary>
  /// 技能信息数据体
  /// </summary>
  public class SkillInfo
  {
    //技能类型 0表示主动 1表示被动
    public int skillType;       
    //技能ID
    public int skillIndex;
    //技能位置，主要用于暂时在客户端显示技能树（暂时没有使用）
    public int skillPos;
    public SkillInfo ()
    {
    }
  }
}

