//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using nh.ui.main;
using nh.ui.model.vo;
using PureMVC.Interfaces;
using PureMVC.Patterns;
using TangGame;
using UnityEngine;

public class GlobalFunction
{
	public GlobalFunction ()
	{
	}
	public static void SendPopMessage(string msg)
	{
		SendPopMessage(msg, MessageVo.OK, "");

	}


	public static void SendPopMessage(string msg, string showState, string title)
	{
		MessageVo vo = new MessageVo();
		vo.content = msg;
		vo.title = title;
		vo.showMode = showState;
		Facade.Instance.SendNotification(NotificationIDs.ID_ShowPopupMessage, vo);
	}
	public static void SendPopMessage(string msg, string showState, string title, string callBackId)
	{
		MessageVo vo = new MessageVo();
		vo.content = msg;
		vo.title = title;
		vo.showMode = showState;
		vo.callBackId = callBackId;
		Facade.Instance.SendNotification(NotificationIDs.ID_ShowPopupMessage, vo);
	}
	/// <summary>
	/// Shows the info at center.
	/// </summary>
	/// <param name="info">Info.</param>
	public static void ShowInfoAtCenter(string info)
	{
		Facade.Instance.SendNotification(NotificationIDs.ID_ShowInfoMessage, info);
	}

	public static GameObject GetRootPanel(){
		UICamera camera =	GameObject.FindObjectOfType<UICamera>();
		if (camera != null)
		{
			UIPanel panel = camera.GetComponentInChildren<UIPanel>();
			if (panel != null)
				return panel.gameObject;

		}
		return null;
	}
	public static double GetCurrentTime()
	{
		TimeSpan ts = DateTime.Now - DateTime.Parse("1970-1-1");
		
		return ts.TotalMilliseconds;
	}
	public static string GetColorString(string str, string color)
	{
		return string.Concat(color, str, "[-]");
	}
}

