//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using nh.ui.mediator;
using PureMVC.Interfaces;
using PureMVC.Patterns;
using nh.ui.model.vo;
namespace nh.ui.utils
{
	public class UIEffectManager : MonoBehaviour
	{
		public Dictionary<string, GameObject> effectDic;
//		public GameObject[] objects;
		public UIEffectManager ()
		{

		}
		void Start()
		{
			effectDic = new Dictionary<string, GameObject>();
			UIEffectMediator mediator = new UIEffectMediator(this);
			Facade.Instance.RegisterMediator(mediator);
			int count = this.transform.childCount;
			for (int i = 0; i < count; i++)
			{
				GameObject obj = this.transform.GetChild(i).gameObject;
				effectDic.Add(obj.name, obj);
			}

		}
		public void showEffect(string effectName)
		{
			if (effectDic.ContainsKey(effectName))
			{
				GameObject obj = effectDic[effectName];
				if (obj)
					obj.SetActive(true);
			}
			else
				Debug.LogWarning(effectName+" not found");
		}
	}
}

