//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TangNet;
namespace TangGame.Net
{
  public class SkillProxy
  {
    public const short TYPE = 0x1200;

    public const short S_STUDY_SKILL = TYPE + 0x0001;      //学习技能
    public const short S_UPLEVEL_SKILL = TYPE + 0x0002;   //技能升级
    public const short S_LIST_SKILLS  = TYPE + 0x0003;    //请求同步技能信息
    public const short S_UPLEVEL_PASSIVE_SKILL = TYPE + 0x004; //升级Passive技能 xbhuang-2013-12-5-16-54

  }
}

