//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TangNet;
using System.Collections.Generic;
using UnityEngine;
namespace TangGame.Net
{
  /// <summary>
  /// 服务器通知更新技能相关
  /// create by huxiaobo
  /// 2013.11.18
  /// </summary>
	[Response(NAME)]
  public class UpdateSkillPush : Response
  {
    public const string NAME = "skillUpdate_PUSH";
    /// <summary>
    /// 英雄ID，暂时没有使用
    /// </summary>
    public long heroId;
    /// <summary>
    /// 技能列表
    /// </summary>
    public List<SkillInfo> skillList;
    public UpdateSkillPush() : base(NAME)
    {
      skillList = new List<SkillInfo>();
    }
    
    public static UpdateSkillPush Parse(MsgData data)
    {      
      UpdateSkillPush push = new UpdateSkillPush();
      push.heroId = data.GetLong(0);
      MsgData datas = data.GetMsgData(1);
      for (int i = 0; i < datas.Size; i++)
      {
        int index = 0;
        MsgData md = datas.GetMsgData(i);

        SkillInfo info = new SkillInfo();
        info.skillType = md.GetInt(index++);
        info.skillIndex = md.GetInt(index++);
        info.skillPos = md.GetInt(index++);
        push.skillList.Add(info);
      }
      return push;
      
    }
  }
}

