//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using TangGame.Net;
using TangGame;
using nh.ui.mediator;
using PureMVC.Interfaces;
using PureMVC.Patterns;
namespace nh.ui.main
{
	/// <summary>
	/// 目标头像面板
	/// create by huxiaobo
	/// </summary>
	public class TargetAvatarPanel : MonoBehaviour
	{
		public UILabel targetNameLabel;		
		public UILabel targetLevel;		
		public UISlider hpProgress;			
		public UISprite headIcon;
		private long objId;
		public long ObjId{
			get{return objId;}
		}
		/// <summary>
		/// 更新面板数据显示
		/// </summary>
		/// <param name="info">Info.</param>
		public void UpdateShow(HeadInfo info)
		{

			if (info != null)
			{
				objId = info.objId;
				if (!string.IsNullOrEmpty(info.headIcon))
				{
					GameObject prefab = PrefabCache.getIconPrefabs(GameConsts.HEAD_ICON_ATLAS, GameConsts.HEAD_ICON_PATH);
					UIAtlas atlas = prefab.GetComponent<UIAtlas>();
					headIcon.atlas = atlas;
	//				headIcon.spriteName = info.headIcon;
					headIcon.spriteName = info.headIcon;
				}
				if (!string.IsNullOrEmpty(info.objName))
					targetNameLabel.text = info.objName;

				targetLevel.text = "Lv" + info.level;
				float value = info.curHp * 1.0f/ info.maxHp;
//				Debug.LogWarning("aaaaaaaaaa"+ value);
				hpProgress.value = value;
			}
		}
		public void ClearData()
		{
			objId = 0;
			headIcon.spriteName = "";
			targetNameLabel.text = "";
			hpProgress.value = 1;
			targetLevel.text = "Lv0";
			
		}
	}
}

