//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PureMVC.Interfaces;
using PureMVC.Patterns;
using nh.ui.panel;
using TangGame;
using UnityEngine;
using TangGame.Xml;
using TangGame.Net;
namespace nh.ui.mediator
{
	/// <summary>
	/// 技能学习界面处理mediator
	/// create by huxiaobo 2013.12.2
	/// </summary>
	public class SkillStudyPanelMediator : Mediator
	{
		public new const string NAME = "SkillStudyPanelMediator";
		protected delegate void Handle(INotification notification);
		protected Dictionary<string, Handle> handleTable = new Dictionary<string, Handle> ();
		protected List<string> interests = new List<string> ();
		private SkillStudyPanel m_Panel;
		public SkillStudyPanelMediator(SkillStudyPanel panel) : base(NAME)
		{
			m_Panel = panel;
//			interests.Add (NotificationIDs.ID_UpdateSkillPanel);
			handleTable.Add (NotificationIDs.ID_UpdateSkillPanel, UpdateSkillPanel);		
		}
		public override IList<string> ListNotificationInterests ()
		{
			if (interests.Count == 0) {
				interests.Add (NotificationIDs.ID_UpdateSkillPanel);
			}
			
			return interests;
		}
		public override void HandleNotification (INotification notification)
		{
			if (handleTable.ContainsKey (notification.Name)) {
				handleTable [notification.Name] (notification);
			}
		}
		/// <summary>
		/// 更新技能面板显示
		/// </summary>
		/// <param name="notification">Notification.</param>
		private void UpdateSkillPanel(INotification notification)
		{
			//			return;
			if (m_Panel == null)//如果技能未初始化，不做处理了
				return;
			
			SkillReflushData srd = notification.Body as SkillReflushData;
			if (srd != null)
			{     
//				SkillPanel sp = m_Panel as SkillPanel;
//				if (sp)
//				{
					foreach (SkillInfo info in srd.skillList)
					{
						m_Panel.UpdateItem(info);
					}
						m_Panel.CheckSkillState();
//				}
				
			}
		}
	}
}

