//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TangNet;
namespace TangGame.Net
{
  /// <summary>
  /// 请求同步技能列表
  /// create by huxiaobo
  /// 2013.11.18
  /// </summary>
  public class SynSkillListRequest : Request
  {
    public SynSkillListRequest()
    {
    }
    public NetData NetData
    {
      get
      {
        NetData data = new NetData(SkillProxy.S_LIST_SKILLS);
        return data;
      }
    }
  }
}

