//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using PureMVC.Interfaces;
using PureMVC.Patterns;
using TangGame.Net;
using System.Collections.Generic;
using UnityEngine;
namespace  TangGame
{
  /// <summary>
  /// 更新技能相关command
  /// create by huxiaobo
  /// 2013.11.18
  /// </summary>
  public class UpdateSkillCommand : SimpleCommand
  {
    public static string NAME = TangGame.Net.UpdateSkillPush.NAME; 
    public override void Execute (INotification notification)
    {
      UpdateSkillPush result = notification.Body as UpdateSkillPush;
      List<SkillInfo> skillList = result.skillList;
      SkillReflushData srd = new SkillReflushData();
      bool needReflush = false;
      int count = 0;
      foreach (SkillInfo info in skillList)
      {
       	SkillsCache.AddSkill(info);
				//更新技能栏
        UpdateHeroUseSkillBarIcon(info);

        //如果是大招则更新大招面板的信息
        if((SkillGroupEnum)Config.skillTable[info.skillIndex].Skill_Group == SkillGroupEnum.DAZHAO ){
          SendNotification(TangGame.NotificationIDs.ID_UPDATE_DAZHAO_SKILL_PANEL);
        }
        count++;
      }

      if (count > 1)
        needReflush = true;
      srd.needReflush = needReflush;
      srd.skillList = skillList;
      SendNotification(NotificationIDs.ID_UpdateSkillPanel, srd);
    }
    /// <summary>
    /// 更新英雄使用技能按钮
    /// </summary>
    public void UpdateHeroUseSkillBarIcon(SkillInfo info){
      List<int> heroUseSkillKeys = new List<int>(SkillsCache.heroUseSkills.Keys);
        for(int i = 0;i<heroUseSkillKeys.Count ; i++){
          int oldKey = heroUseSkillKeys[i];
          //对比两个技能是否相同
          if(Config.skillTable[info.skillIndex].Sort 
             == Config.skillTable[oldKey].Sort){
            TangGame.Net.Skill skill = SkillsCache.heroUseSkills[oldKey];
            skill.id = info.skillIndex;
            SkillsCache.heroUseSkills.Remove(oldKey);
            SkillsCache.heroUseSkills.Add(skill.id,skill);
            SkillBarBean bean = new SkillBarBean(skill.skillBarIndex,skill.id);
            SendNotification(NtftNames.TG_UPDATE_SKILL_BAR, bean);
          }
        }
    }
  }
}

